### ISSUE TITLE
Unit test Menu component

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#170]
The Menu component has a significant JavaScript component to it and we are currently unable to test this component without injecting a JavaScript Interop with bUnit.

@egil can you help us set a standard in our project for testing components that need the JavaScript interop?

**Comment by egil** [comment]
The general recommendation is to treat JSInterop calls as web service calls, thus, like we would in a normal testing scenario involving web services, we abstract the code that performs the actual JSInterop calls using e.g. an interface, which we can mock during testing. If it is very few calls, or the calls between the Blazor component and JS is simple, then the easiest is to just use the MockJSInterop that is part of bUnit.

How many calls will there be between the JavaScript part of the menu component and the Blazor part?

I took a quick search through the feature branch, and only saw this: https://github.com/FritzAndFriends/BlazorWebFormsComponents/blob/feature_Menu/src/BlazorWebFormsComponents/Menu.razor.cs#L51

If there is only one, and the rest of the menu component is driven by the Menu.js logic, then this might suffice:

```c#
<Fixture>...</Fixture>

public void MenuComponentInitsMenuJsAtFirstRender(Fixture fixture)
{
    var jsMock = fixture.Services.AddMockJsRuntime();
    
    var cut = fixture.GetComponentUnderTest();
    
    jsMock.VerifyInvoke("bwfc.Page.AddScriptElement");
}
```

This will verify that the invocation happened. In addition, you should add tests that verify that the component generates the HMTL expected by the Javascript.

To test the actual JavaScript, you need something other than bUnit, since it does not run JavaScript. 

Unfortunately, the mock jsinterop in bUnit is not super well documented yet, but here are some exmaples:

- https://github.com/egil/bunit/blob/master/sample/tests/Tests/Components/WikiSearchTest.cs
- https://github.com/egil/bunit/blob/master/sample/tests/Tests/Components/TodoListTest.cs#L80

**Comment by csharpfritz** [comment]
This was a huge help!  We now have our Menu component unit testing successfully.  Check /src/BlazorWebFormsComponents.Test/Menu/DocsSample.razor@feature_Menu
