### ISSUE TITLE
Collections properties throws an expection with GridView

### ISSUE THREAD

**Issue by hishamco** [FritzAndFriends/BlazorWebFormsComponents#203]
This is related to #128, we need to ignore collections properties with `AutoGeneratedColumns` and bound it with Template Fields

**Comment by hishamco** [comment]
I'm working on this one ...

**Comment by Eilon** [comment]
@hishamco do you have an example of what doesn't work right now?

Also, this might be related to this change I just submitted: https://github.com/FritzAndFriends/BlazorWebFormsComponents/pull/223

Using Reflection often is a source of these types of problems. My change removes most usage of Reflection, so perhaps it also fixes this issue here?

**Comment by hishamco** [comment]
Try to add a class which has a collection property and bind it with the `GridView` with `AutoGeneratedColumns` enabled

**Comment by Eilon** [comment]
Got it. I can try to take a look if you're busy with your recovery.

**Comment by hishamco** [comment]
I already started on this, I can continue working on it, but it would be nice to merge your PR first coz there low level reflections have been removed

Thanks

**Comment by Eilon** [comment]
In System.Web there was this helper method that I think was used to determine which properties were bindable by default:

https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System.Web/UI/WebControls/DataBoundControlHelper.cs#L79
