### ISSUE TITLE
Handle LayoutTemplates

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/BlazorWebFormsComponents#28]
For controls like ListView, there are LayoutTemplate elements that declares the outer rendering for the component.  There is typically a an ItemPlaceholderId attribute that defines an element id inside the LayoutTemplate where in the LayoutTemplate the contents of the component should be inserted.

```html
<asp:ListView ItemPlaceholderId="foo">
	<LayoutTemplate>
	<span id="foo"></span>
	</LayoutTemplate>
</asp:ListView>
```

should render something like:

```html
<span id="foo">
  == LISTVIEW CONTENT ==
</span>

**Comment by SQL-MisterMagoo** [comment]
I have made some progress on this and hope to share something this weekend.

**Comment by csharpfritz** [comment]
Ooh!  Did any of the code I started in the spike branch help with your attempt at templates?



Jeff

**Comment by SQL-MisterMagoo** [comment]
I started with a blank slate.

**Comment by SQL-MisterMagoo** [comment]
Here's the main problem - a section of markup on the page is treated in two basic ways.

1. Plain html markup
2. Razor/C# code

When you define a RenderFragment e.g. LayoutTemplate and the developer populates it like this

``` HTML
    <LayoutTemplate>
        <div class="container">
            <h2>This is my outer List</h2>
            <div>I expect my Items below here as cards</div>
            <span id="abc123"></span>
        </div>
    </LayoutTemplate>
```

Then the Razor compiler will create the following code (this is just the bit we care about):

``` CSharp
__builder2.AddMarkupContent(6, "<div class=\"container\">\r\n            <h2>This is my outer List</h2>\r\n            <div>I expect my Items below here as cards</div>\r\n            <span id=\"abc123\"></span>\r\n        </div>\r\n    ");
```
You notice that the entire template is added as a section of MarkupContent.

We can inspect that MarkupContent and figure out where to inject data, but we can't just render the items and inject them in as MarkupContent - as getting the renderd HTML is not really possible and anyway the list items might have Blazor directives in the item template that would not work as MarkupContent.

If you include some Razor/C# code in the template like this
``` HTML
    <LayoutTemplate>
        <div class="container">
            <h2>This is my outer List</h2>
            <div>I expect my Items below here as cards</div>
            <span id="abc123">@("")</span>
        </div>
    </LayoutTemplate>
```
This then gets compiled as elements with attributes, which could be manipulated more easily

``` CSharp
            __builder.AddAttribute(4, "LayoutTemplate", (Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(5, "\r\n        ");
                __builder2.OpenElement(6, "div");
                __builder2.AddAttribute(7, "class", "container");
                __builder2.AddMarkupContent(8, "\r\n            ");
                __builder2.AddMarkupContent(9, "<h2>This is my outer List</h2>\r\n            ");
                __builder2.AddMarkupContent(10, "<div>I expect my Items below here as cards</div>\r\n            ");
                __builder2.OpenElement(11, "span");
                __builder2.AddAttribute(12, "id", "abc123");
                __builder2.AddContent(13, 
#nullable restore
#line 12 "C:\Users\miste\source\repos\BlazorApp1\BlazorApp1\Pages\Index.razor"
                                ""

#line default
#line hidden
#nullable disable
                );
                __builder2.CloseElement();
                __builder2.AddMarkupContent(14, "\r\n        ");
                __builder2.CloseElement();
                __builder2.AddMarkupContent(15, "\r\n    ");
            }
            ));
```
At least with this in the render tree, we can analyse it, pick out the placeholder and inject our data list items as Content.
However, if the template needs some Razor/C# in order to get the compiler to break the layout into composable elements, then why bother with all this as we could just use standard functionality.

### Recommendation

When it comes down to it, the WebForms code will need to be modified anyway to replace the bee-sting syntax with Razor syntax ( @ Something ), so my advice is to require that here as well.

You cannot have code like this in Blazor
``` HTML
<ItemTemplate>
      <tr runat="server">
        <td>
          <asp:LinkButton ID="EditButton" runat="Server" Text="Edit" CommandName="Edit" />
        </td>
        <td>
          <asp:Label ID="FirstNameLabel" runat="Server" Text='<%#Eval("FirstName") %>' />
        </td>
        <td valign="top">
          <asp:Label ID="LastNameLabel" runat="Server" Text='<%#Eval("LastName") %>' />
        </td>
      </tr>
</ItemTemplate>
```
The `<%#Eval("...")%>` code has to go, and if you accept that change is inevitable, you can have this working right now,

``` HTML
<ListView TItem="string" Data=Data>
    <LayoutTemplate Context="itemPlaceHolder">
        <div class="container">
            <h2>This is my outer List</h2>
            <div>I expect my Items below here as cards</div>
            @itemPlaceHolder
        </div>
    </LayoutTemplate>
    <ItemTemplate Context="Item">
        <div class="card">
            <div class="card-header">
                <label>My item : @Item</label>
            </div>
        </div>
    </ItemTemplate>
</ListView>
```

**Comment by csharpfritz** [comment]
Oh yea, the Eval databinding is not going to work... and should be
converted to strongly-typed Item.Something notation

I can absolutely take the consideration of placing an @() where the
template contents should be rendered.  That feels like a small price to pay
to get the templating functionality working properly.


Jeff

**Comment by SQL-MisterMagoo** [comment]
I have sent a PR with the Layout template working as described above with `@itemPlaceHolder`

Feel free to ask questions about the implementation, but I hope it is obvious enough - it's just getting your head around the change to make  LayoutTemplate a `RenderFragment<RenderFragment>` that is the key.

If you view the diff ignoring whitespace - there are not too many changes to the core component.

https://github.com/FritzAndFriends/BlazorWebFormsComponents/pull/32/files?utf8=%E2%9C%93&diff=split&w=1
